export const questions = [
  { id: 1, question: 'What is your name?', type: 'text' },
  { id: 2, question: 'How old are you?', type: 'slider', min: 12, max: 100 },
  { id: 3, question: 'What is your main fitness goal?', type: 'radio', options: ['Lose weight', 'Build muscle', 'Improve endurance', 'Other'] },
  { id: 4, question: 'How do you rate your fitness level?', type: 'radio', options: ['Beginner', 'Intermediate', 'Advanced'] },
  { id: 5, question: 'How much time can you dedicate to training per week?', type: 'radio', options: ['Less than 2 hours', '2–4 hours', 'More than 4 hours'] },
  { id: 6, question: 'Do you have access to workout equipment?', type: 'radio', options: ['Yes', 'No', 'Only basic equipment'] },
  { id: 7, question: 'Which muscle groups are your priority?', type: 'radio', options: ['Legs', 'Back', 'Arms', 'Abs', 'Full body', 'Other'] },
  { id: 8, question: 'Do you have any health limitations?', type: 'radio', options: ['Yes', 'No'] },
  { id: 9, question: 'How do you rate your physical condition?', type: 'radio', options: ['Poor', 'Average', 'Good', 'Very good'] },
  { id: 10, question: 'Do you prefer working out at home or at the gym?', type: 'radio', options: ['Home', 'Gym', 'No preference'] },
  { id: 11, question: 'What is your current height?', type: 'slider', min: 65, max: 250, unit: 'cm' },
  { id: 12, question: 'What is your current weight?', type: 'slider', min: 20, max: 300, unit: 'kg' },
  { id: 14, question: 'Are you interested in a specific type of training?', type: 'radio', options: ['Strength', 'Cardio', 'HIIT', 'Stretching', 'Other'] },
  { id: 15, question: 'What are your dietary preferences?', type: 'radio', options: ['Vegan', 'Vegetarian', 'Traditional', 'Other'] },
];
